### ISSUE TITLE
Color banding in shadows

### ISSUE THREAD

**Issue by yagomont** [zzag/material-decoration#1]
I ask for assistance on the shadows of this project, because of a noticeable artifact in certain light conditions. (and also because I have no clue why the shadows are so big even after looking at the code. In fact, I never saw something like Qt-containing code in my life.)

Unfortunately, after seeing that the effect was still present in Breeze I pretty much think fixing this is impossible. A difference, though, is that the Breeze shadow is more... compact? It has more color bands going on, which makes it only noticeable if you put your eyes up close. If we can reproduce this in material-decoration, that'd be great. Because, it's pretty jarring right now.

But that won't stop me from using it, btw (because it's awesome). I've been using this decoration since last year, and, it's pretty much public-ready. Don't hold back!

How can we fix this?

Here are some contextual images. (may not reproduce real-life effects due to compression and what-not)
![screenshot_20190122_205855](https://user-images.githubusercontent.com/14876659/51573738-4d6f3f80-1e89-11e9-8b35-6404a4644f93.png)

![light](https://user-images.githubusercontent.com/14876659/51573736-4cd6a900-1e89-11e9-852f-c220e4e726a6.png)
![screenshot_20190122_205515](https://user-images.githubusercontent.com/14876659/51573737-4d6f3f80-1e89-11e9-8665-def710043841.png)

**Comment by zzag** [comment]
> How can we fix this?

Well, it's complicated. The banding is noticeable only with dark backgrounds.

One option is to wait `N` years until a better kind of displays is invented.

The other option is to change the shadow color to pure black and also decrease the size.

**Comment by yagomont** [comment]
How do I decrease the size in the code? It's what I want to do, actually.

**Comment by zzag** [comment]
> How do I decrease the size in the code? It's what I want to do, actually.

The relevant part of the code:
* https://github.com/zzag/material-decoration/blob/master/src/Decoration.cc#L71-L75
* https://github.com/zzag/material-decoration/blob/master/src/Decoration.cc#L80

For reference, here are shadow params from the Breeze decoration theme:
https://github.com/KDE/breeze/blob/master/kdecoration/breezedecoration.cpp#L101-L124

**Comment by yagomont** [comment]
That's what I was looking for. Thanks.
Mind if I fork this? It's now got the breeze shadows I regard as looking nice and integrates with luwx's fluent-kvantum well having the same color as the window content.

Edit: It's free software, so I'll just go ahead.

**Comment by zzag** [comment]
> Edit: It's free software, so I'll just go ahead.

Yes, that's the whole point. :-)
